name: UpdateSnapTests

on:
  pull_request:
    paths:
      - 'updatesnap/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pylint
        python3 -m pip install flake8
        python3 -m pip install requests
        python3 -m pip install pyyaml
        python3 -m pip install python-debian
    - name: Code tests
      env:
        GITHUB_USER: ubuntu
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        cd updatesnap
        ./unittests.py
    - name: Analysing the code with pylint and flake8
      run: |
        cd updatesnap
        ./style_check.sh
